/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"beneficiaryName": "beneficiaryName",
		"swiftMessage": "swiftMessage",
		"swiftMessageType": "swiftMessageType",
		"swiftDate": "swiftDate",
		"swiftCategory": "swiftCategory",
		"drawingsSrmsRequestOrderID": "drawingsSrmsRequestOrderID",
		"swiftsAndAdvicesSrmsRequestOrderID": "swiftsAndAdvicesSrmsRequestOrderID",
		"customerId": "customerId",
		"errorMessage": "errorMessage",
		"errorCode": "errorCode",
		"flowType": "flowType",
		"status": "status",
		"sender": "sender",
		"receiver": "receiver",
		"guaranteesAmendId": "guaranteesAmendId",
		"adviceName": "adviceName",
		"messageDate": "messageDate",
		"messageType": "messageType",
		"message": "message",
		"module": "module",
		"createdDate": "createdDate",
		"orderId": "orderId",
		"bCode": "bCode",
		"bic": "bic",
		"transferDateOrTime": "transferDateOrTime",
		"type": "type",
		"requestedDateOfIssue": "requestedDateOfIssue",
		"formOfUndertaking": "formOfUndertaking",
		"applicableRules": "applicableRules",
		"typeOfUndertaking": "typeOfUndertaking",
		"expiryType": "expiryType",
		"dateOfExpiry": "dateOfExpiry",
		"expiryConditionOrEvent": "expiryConditionOrEvent",
		"applicant": "applicant",
		"obligorOrInstructingParty": "obligorOrInstructingParty",
		"issuer": "issuer",
		"beneficiary": "beneficiary",
		"undertakingAmount": "undertakingAmount",
		"additionalAmountInformation": "additionalAmountInformation",
		"availableWith": "availableWith",
		"charges": "charges",
		"documentAndPresentationInstructions": "documentAndPresentationInstructions",
		"requestedLocalUndertakingTermsAndConditions": "requestedLocalUndertakingTermsAndConditions",
		"standardWordingRequired": "standardWordingRequired",
		"standardWordingRequestedLanguage": "standardWordingRequestedLanguage",
		"governingLawAndOrPlaceOfJurisdiction": "governingLawAndOrPlaceOfJurisdiction",
		"automaticExtensionPeriod": "automaticExtensionPeriod",
		"automaticExtensionNonExtensionPeriod": "automaticExtensionNonExtensionPeriod",
		"automaticExtensionNotificationPeriod": "automaticExtensionNotificationPeriod",
		"automaticExtensionFinalExpiryDate": "automaticExtensionFinalExpiryDate",
		"demandIndicator": "demandIndicator",
		"transferIndicator": "transferIndicator",
		"transferConditions": "transferConditions",
		"underlyingTransactionDetails": "underlyingTransactionDetails",
		"deliveryOfLocalUndertaking": "deliveryOfLocalUndertaking",
		"deliveryToOrCollectionBy": "deliveryToOrCollectionBy",
		"newSequence": "newSequence",
		"product": "product",
		"fileName": "fileName",
		"fileId": "fileId",
		"category": "category",
		"uploadedTimeStamp": "uploadedTimeStamp",
	};

	Object.freeze(mappings);

	var typings = {
		"beneficiaryName": "string",
		"swiftMessage": "string",
		"swiftMessageType": "string",
		"swiftDate": "string",
		"swiftCategory": "string",
		"drawingsSrmsRequestOrderID": "string",
		"swiftsAndAdvicesSrmsRequestOrderID": "string",
		"customerId": "string",
		"errorMessage": "string",
		"errorCode": "string",
		"flowType": "string",
		"status": "string",
		"sender": "string",
		"receiver": "string",
		"guaranteesAmendId": "string",
		"adviceName": "string",
		"messageDate": "string",
		"messageType": "string",
		"message": "string",
		"module": "string",
		"createdDate": "string",
		"orderId": "string",
		"bCode": "string",
		"bic": "string",
		"transferDateOrTime": "string",
		"type": "string",
		"requestedDateOfIssue": "string",
		"formOfUndertaking": "string",
		"applicableRules": "string",
		"typeOfUndertaking": "string",
		"expiryType": "string",
		"dateOfExpiry": "string",
		"expiryConditionOrEvent": "string",
		"applicant": "string",
		"obligorOrInstructingParty": "string",
		"issuer": "string",
		"beneficiary": "string",
		"undertakingAmount": "string",
		"additionalAmountInformation": "string",
		"availableWith": "string",
		"charges": "string",
		"documentAndPresentationInstructions": "string",
		"requestedLocalUndertakingTermsAndConditions": "string",
		"standardWordingRequired": "string",
		"standardWordingRequestedLanguage": "string",
		"governingLawAndOrPlaceOfJurisdiction": "string",
		"automaticExtensionPeriod": "string",
		"automaticExtensionNonExtensionPeriod": "string",
		"automaticExtensionNotificationPeriod": "string",
		"automaticExtensionFinalExpiryDate": "string",
		"demandIndicator": "string",
		"transferIndicator": "string",
		"transferConditions": "string",
		"underlyingTransactionDetails": "string",
		"deliveryOfLocalUndertaking": "string",
		"deliveryToOrCollectionBy": "string",
		"newSequence": "string",
		"product": "string",
		"fileName": "string",
		"fileId": "string",
		"category": "string",
		"uploadedTimeStamp": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"swiftsAndAdvicesSrmsRequestOrderID",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "TradeFinance",
		tableName: "SwiftsAndAdvices"
	};

	Object.freeze(config);

	return config;
})