/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"allowUsanceAcceptance": "allowUsanceAcceptance",
		"amendTenorType": "amendTenorType",
		"amendmentNo": "amendmentNo",
		"amendmentReference": "amendmentReference",
		"amount": "amount",
		"billOfExchangeStatus": "billOfExchangeStatus",
		"cancellationStatus": "cancellationStatus",
		"chargesDebitAccount": "chargesDebitAccount",
		"collectingBank": "collectingBank",
		"collectingBankAddress": "collectingBankAddress",
		"collectionReference": "collectionReference",
		"corporateUserName": "corporateUserName",
		"courierTrackingDetails": "courierTrackingDetails",
		"createdOn": "createdOn",
		"creditAccount": "creditAccount",
		"currency": "currency",
		"dbpErrCode": "dbpErrCode",
		"dbpErrMsg": "dbpErrMsg",
		"debitAccount": "debitAccount",
		"deliveryInstructions": "deliveryInstructions",
		"documentNo": "documentNo",
		"draweeAcceptance": "draweeAcceptance",
		"draweeAcknowledgement": "draweeAcknowledgement",
		"draweeAddress": "draweeAddress",
		"draweeName": "draweeName",
		"errorCode": "errorCode",
		"errorMsg": "errorMsg",
		"incoTerms": "incoTerms",
		"instructionsForBills": "instructionsForBills",
		"isBillExchangeSigned": "isBillExchangeSigned",
		"lastAmendmentDetails": "lastAmendmentDetails",
		"maturityDate": "maturityDate",
		"messageFromBank": "messageFromBank",
		"messageToBank": "messageToBank",
		"otherCollectionDetails": "otherCollectionDetails",
		"paymentStatus": "paymentStatus",
		"physicalDocuments": "physicalDocuments",
		"reasonForRejection": "reasonForRejection",
		"reasonForReturn": "reasonForReturn",
		"requestedOn": "requestedOn",
		"returnedHistory": "returnedHistory",
		"status": "status",
		"swiftOrBicCode": "swiftOrBicCode",
		"tenorType": "tenorType",
		"updatedOn": "updatedOn",
		"uploadDocuments": "uploadDocuments",
		"usanceDays": "usanceDays",
		"usanceDetails": "usanceDetails",
		"searchString": "searchString",
		"pageSize": "pageSize",
		"pageOffset": "pageOffset",
		"sortByParam": "sortByParam",
		"sortOrder": "sortOrder",
		"timeParam": "timeParam",
		"timeValue": "timeValue",
		"filterByValue": "filterByValue",
		"filterByParam": "filterByParam",
		"reasonForCancellation": "reasonForCancellation",
		"requestPaymentStatus": "requestPaymentStatus",
		"requestBillOfExchange": "requestBillOfExchange",
		"requestSelection": "requestSelection",
	};

	Object.freeze(mappings);

	var typings = {
		"allowUsanceAcceptance": "string",
		"amendTenorType": "string",
		"amendmentNo": "string",
		"amendmentReference": "string",
		"amount": "string",
		"billOfExchangeStatus": "string",
		"cancellationStatus": "string",
		"chargesDebitAccount": "string",
		"collectingBank": "string",
		"collectingBankAddress": "string",
		"collectionReference": "string",
		"corporateUserName": "string",
		"courierTrackingDetails": "string",
		"createdOn": "string",
		"creditAccount": "string",
		"currency": "string",
		"dbpErrCode": "string",
		"dbpErrMsg": "string",
		"debitAccount": "string",
		"deliveryInstructions": "string",
		"documentNo": "string",
		"draweeAcceptance": "string",
		"draweeAcknowledgement": "string",
		"draweeAddress": "string",
		"draweeName": "string",
		"errorCode": "string",
		"errorMsg": "string",
		"incoTerms": "string",
		"instructionsForBills": "string",
		"isBillExchangeSigned": "string",
		"lastAmendmentDetails": "string",
		"maturityDate": "string",
		"messageFromBank": "string",
		"messageToBank": "string",
		"otherCollectionDetails": "string",
		"paymentStatus": "string",
		"physicalDocuments": "string",
		"reasonForRejection": "string",
		"reasonForReturn": "string",
		"requestedOn": "string",
		"returnedHistory": "string",
		"status": "string",
		"swiftOrBicCode": "string",
		"tenorType": "string",
		"updatedOn": "string",
		"uploadDocuments": "string",
		"usanceDays": "string",
		"usanceDetails": "string",
		"searchString": "string",
		"pageSize": "string",
		"pageOffset": "string",
		"sortByParam": "string",
		"sortOrder": "string",
		"timeParam": "string",
		"timeValue": "string",
		"filterByValue": "string",
		"filterByParam": "string",
		"reasonForCancellation": "string",
		"requestPaymentStatus": "string",
		"requestBillOfExchange": "string",
		"requestSelection": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"collectionReference",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "TradeFinance",
		tableName: "OutwardCollections"
	};

	Object.freeze(config);

	return config;
})