/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"searchString": "searchString",
		"pageSize": "pageSize",
		"pageOffset": "pageOffset",
		"sortByParam": "sortByParam",
		"sortOrder": "sortOrder",
		"timeParam": "timeParam",
		"timeValue": "timeValue",
		"filterByValue": "filterByValue",
		"filterByParam": "filterByParam",
		"dbpErrCode": "dbpErrCode",
		"dbpErrMsg": "dbpErrMsg",
		"lcReferenceNo": "lcReferenceNo",
		"exportLCId": "exportLCId",
		"drawingReferenceNo": "drawingReferenceNo",
		"drawingSRMSRequestId": "drawingSRMSRequestId",
		"drawingAmount": "drawingAmount",
		"lcType": "lcType",
		"issuingBankReference": "issuingBankReference",
		"advisingBankReference": "advisingBankReference",
		"applicant": "applicant",
		"utilizedLCAmount": "utilizedLCAmount",
		"issueDate": "issueDate",
		"amount": "amount",
		"expiryDate": "expiryDate",
		"currency": "currency",
		"issuingBank": "issuingBank",
		"applicantaddress": "applicantaddress",
		"issuingbankaddress": "issuingbankaddress",
		"paymentTerms": "paymentTerms",
		"documentName": "documentName",
		"uploadedFiles": "uploadedFiles",
		"forwardContract": "forwardContract",
		"beneficiaryName": "beneficiaryName",
		"beneficiaryAddress": "beneficiaryAddress",
		"goodsDescription": "goodsDescription",
		"additionalConditions": "additionalConditions",
		"confirmInstructions": "confirmInstructions",
		"latestShipmentDate": "latestShipmentDate",
		"amendmentChargesPayer": "amendmentChargesPayer",
		"amendmentReceivedDate": "amendmentReceivedDate",
		"exportlcReferenceNo": "exportlcReferenceNo",
		"exportlcSRMSRequestId": "exportlcSRMSRequestId",
		"status": "status",
		"lcCreatedOn": "lcCreatedOn",
		"financeBill": "financeBill",
		"creditAccount": "creditAccount",
		"externalAccount": "externalAccount",
		"chargesDebitAccount": "chargesDebitAccount",
		"messageToBank": "messageToBank",
		"physicalDocuments": "physicalDocuments",
		"uploadedDocuments": "uploadedDocuments",
		"forwardDocuments": "forwardDocuments",
		"lcAmount": "lcAmount",
		"lcCurrency": "lcCurrency",
		"lcIssueDate": "lcIssueDate",
		"paymentDate": "paymentDate",
		"totalDocuments": "totalDocuments",
		"documentStatus": "documentStatus",
		"discrepencies": "discrepencies",
		"discrepenciesAcceptance": "discrepenciesAcceptance",
		"paymentStatus": "paymentStatus",
		"totalAmount": "totalAmount",
		"reasonForReturn": "reasonForReturn",
		"drawingCreatedDate": "drawingCreatedDate",
		"discrepanciesHistory1": "discrepanciesHistory1",
		"discrepanciesHistory2": "discrepanciesHistory2",
		"discrepanciesHistory3": "discrepanciesHistory3",
		"fileId": "fileId",
		"documentReference": "documentReference",
		"returnMessageToBank": "returnMessageToBank",
		"newLcAmount": "newLcAmount",
		"amendmentStatus": "amendmentStatus",
		"periodOfPresentation": "periodOfPresentation",
		"reasonForSelfRejection": "reasonForSelfRejection",
		"applicantName": "applicantName",
		"amendmentNo": "amendmentNo",
		"amendmentSRMSRequestId": "amendmentSRMSRequestId",
		"selfRejectedDate": "selfRejectedDate",
		"amendmentReferenceNo": "amendmentReferenceNo",
		"oldLcAmount": "oldLcAmount",
		"selfAcceptance": "selfAcceptance",
		"otherAmendments": "otherAmendments",
		"lcAmountStatus": "lcAmountStatus",
		"lcExpiryDate": "lcExpiryDate",
		"selfAcceptanceDate": "selfAcceptanceDate",
		"lcUpdatedOn": "lcUpdatedOn",
		"beneficiaryConsent": "beneficiaryConsent",
		"reasonForRejection": "reasonForRejection",
	};

	Object.freeze(mappings);

	var typings = {
		"searchString": "string",
		"pageSize": "string",
		"pageOffset": "string",
		"sortByParam": "string",
		"sortOrder": "string",
		"timeParam": "string",
		"timeValue": "string",
		"filterByValue": "string",
		"filterByParam": "string",
		"dbpErrCode": "string",
		"dbpErrMsg": "string",
		"lcReferenceNo": "string",
		"exportLCId": "string",
		"drawingReferenceNo": "string",
		"drawingSRMSRequestId": "string",
		"drawingAmount": "string",
		"lcType": "string",
		"issuingBankReference": "string",
		"advisingBankReference": "string",
		"applicant": "string",
		"utilizedLCAmount": "string",
		"issueDate": "string",
		"amount": "string",
		"expiryDate": "string",
		"currency": "string",
		"issuingBank": "string",
		"applicantaddress": "string",
		"issuingbankaddress": "string",
		"paymentTerms": "string",
		"documentName": "string",
		"uploadedFiles": "string",
		"forwardContract": "string",
		"beneficiaryName": "string",
		"beneficiaryAddress": "string",
		"goodsDescription": "string",
		"additionalConditions": "string",
		"confirmInstructions": "string",
		"latestShipmentDate": "string",
		"amendmentChargesPayer": "string",
		"amendmentReceivedDate": "string",
		"exportlcReferenceNo": "string",
		"exportlcSRMSRequestId": "string",
		"status": "string",
		"lcCreatedOn": "string",
		"financeBill": "string",
		"creditAccount": "string",
		"externalAccount": "string",
		"chargesDebitAccount": "string",
		"messageToBank": "string",
		"physicalDocuments": "string",
		"uploadedDocuments": "string",
		"forwardDocuments": "string",
		"lcAmount": "string",
		"lcCurrency": "string",
		"lcIssueDate": "string",
		"paymentDate": "string",
		"totalDocuments": "string",
		"documentStatus": "string",
		"discrepencies": "string",
		"discrepenciesAcceptance": "string",
		"paymentStatus": "string",
		"totalAmount": "string",
		"reasonForReturn": "string",
		"drawingCreatedDate": "string",
		"discrepanciesHistory1": "string",
		"discrepanciesHistory2": "string",
		"discrepanciesHistory3": "string",
		"fileId": "string",
		"documentReference": "string",
		"returnMessageToBank": "string",
		"newLcAmount": "string",
		"amendmentStatus": "string",
		"periodOfPresentation": "string",
		"reasonForSelfRejection": "string",
		"applicantName": "string",
		"amendmentNo": "string",
		"amendmentSRMSRequestId": "string",
		"selfRejectedDate": "string",
		"amendmentReferenceNo": "string",
		"oldLcAmount": "string",
		"selfAcceptance": "string",
		"otherAmendments": "string",
		"lcAmountStatus": "string",
		"lcExpiryDate": "string",
		"selfAcceptanceDate": "string",
		"lcUpdatedOn": "string",
		"beneficiaryConsent": "string",
		"reasonForRejection": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"lcReferenceNo",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "TradeFinance",
		tableName: "ExportLetterOfCredit"
	};

	Object.freeze(config);

	return config;
})