/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"lcReferenceNo": "lcReferenceNo",
		"lcAmount": "lcAmount",
		"lcCurrency": "lcCurrency",
		"tolerancePercentage": "tolerancePercentage",
		"maximumCreditAmount": "maximumCreditAmount",
		"additionalAmountPayable": "additionalAmountPayable",
		"paymentTerms": "paymentTerms",
		"availableWith1": "availableWith1",
		"availableWith2": "availableWith2",
		"availableWith3": "availableWith3",
		"availableWith4": "availableWith4",
		"issueDate": "issueDate",
		"expiryDate": "expiryDate",
		"expiryPlace": "expiryPlace",
		"chargesAccount": "chargesAccount",
		"commisionAccount": "commisionAccount",
		"marginAccount": "marginAccount",
		"messageToBank": "messageToBank",
		"beneficiaryName": "beneficiaryName",
		"beneficiaryAddressLine1": "beneficiaryAddressLine1",
		"beneficiaryAddressLine2": "beneficiaryAddressLine2",
		"beneficiaryPostCode": "beneficiaryPostCode",
		"beneficiaryCountry": "beneficiaryCountry",
		"beneficiaryCity": "beneficiaryCity",
		"beneficiaryState": "beneficiaryState",
		"beneficiaryBank": "beneficiaryBank",
		"beneficiaryBankAdressLine1": "beneficiaryBankAdressLine1",
		"beneficiaryBankAdressLine2": "beneficiaryBankAdressLine2",
		"beneficiaryBankPostCode": "beneficiaryBankPostCode",
		"beneficiaryBankCountry": "beneficiaryBankCountry",
		"beneficiaryBankCity": "beneficiaryBankCity",
		"beneficiaryBankState": "beneficiaryBankState",
		"placeOfTakingIncharge": "placeOfTakingIncharge",
		"portOfLoading": "portOfLoading",
		"portOfDischarge": "portOfDischarge",
		"placeOfFinalDelivery": "placeOfFinalDelivery",
		"latestShippingDate": "latestShippingDate",
		"presentationPeriod": "presentationPeriod",
		"transshipment": "transshipment",
		"partialShipments": "partialShipments",
		"incoTerms": "incoTerms",
		"modeOfShipment": "modeOfShipment",
		"descriptionOfGoods": "descriptionOfGoods",
		"documentsRequired": "documentsRequired",
		"additionalConditionsCode": "additionalConditionsCode",
		"otherAdditionalConditions": "otherAdditionalConditions",
		"documentCharges": "documentCharges",
		"supportDocuments": "supportDocuments",
		"fileToUpload": "fileToUpload",
		"confirmationInstruction": "confirmationInstruction",
		"transferable": "transferable",
		"standByLC": "standByLC",
		"isDraft": "isDraft",
		"additionalPayableCurrency": "additionalPayableCurrency",
		"code": "code",
		"msg": "msg",
		"flowType": "flowType",
		"id": "id",
		"amendStatus": "amendStatus",
		"ErrorCode": "ErrorCode",
		"ErrorMessage": "ErrorMessage",
		"srmsReqOrderID": "srmsReqOrderID",
		"lcCreatedOn": "lcCreatedOn",
		"draftCount": "draftCount",
		"draftAmount": "draftAmount",
		"deletedCount": "deletedCount",
		"deletedAmount": "deletedAmount",
		"selfApprovedCount": "selfApprovedCount",
		"selfApprovedAmount": "selfApprovedAmount",
		"totalCount": "totalCount",
		"totalAmount": "totalAmount",
		"fileId": "fileId",
		"amountType": "amountType",
		"otherAmendments": "otherAmendments",
		"amendCharges": "amendCharges",
		"chargesPaid": "chargesPaid",
		"creditAmount": "creditAmount",
		"amendmentReference": "amendmentReference",
		"amendmentDate": "amendmentDate",
		"amendmentApprovedDate": "amendmentApprovedDate",
		"lcType": "lcType",
		"amendmentExpiryDate": "amendmentExpiryDate",
		"utilizedAmount": "utilizedAmount",
		"importLCId": "importLCId",
		"referenceNomatch": "referenceNomatch",
		"lcSRMSId": "lcSRMSId",
		"branchName": "branchName",
		"country": "country",
		"city": "city",
		"bankName": "bankName",
		"iban": "iban",
		"bic": "bic",
		"countryRegion": "countryRegion",
		"zipcode": "zipcode",
		"bankAddress": "bankAddress",
	};

	Object.freeze(mappings);

	var typings = {
		"lcReferenceNo": "string",
		"lcAmount": "string",
		"lcCurrency": "string",
		"tolerancePercentage": "string",
		"maximumCreditAmount": "string",
		"additionalAmountPayable": "string",
		"paymentTerms": "string",
		"availableWith1": "string",
		"availableWith2": "string",
		"availableWith3": "string",
		"availableWith4": "string",
		"issueDate": "string",
		"expiryDate": "string",
		"expiryPlace": "string",
		"chargesAccount": "string",
		"commisionAccount": "string",
		"marginAccount": "string",
		"messageToBank": "string",
		"beneficiaryName": "string",
		"beneficiaryAddressLine1": "string",
		"beneficiaryAddressLine2": "string",
		"beneficiaryPostCode": "string",
		"beneficiaryCountry": "string",
		"beneficiaryCity": "string",
		"beneficiaryState": "string",
		"beneficiaryBank": "string",
		"beneficiaryBankAdressLine1": "string",
		"beneficiaryBankAdressLine2": "string",
		"beneficiaryBankPostCode": "string",
		"beneficiaryBankCountry": "string",
		"beneficiaryBankCity": "string",
		"beneficiaryBankState": "string",
		"placeOfTakingIncharge": "string",
		"portOfLoading": "string",
		"portOfDischarge": "string",
		"placeOfFinalDelivery": "string",
		"latestShippingDate": "string",
		"presentationPeriod": "string",
		"transshipment": "string",
		"partialShipments": "string",
		"incoTerms": "string",
		"modeOfShipment": "string",
		"descriptionOfGoods": "string",
		"documentsRequired": "string",
		"additionalConditionsCode": "string",
		"otherAdditionalConditions": "string",
		"documentCharges": "string",
		"supportDocuments": "string",
		"fileToUpload": "string",
		"confirmationInstruction": "string",
		"transferable": "string",
		"standByLC": "string",
		"isDraft": "string",
		"additionalPayableCurrency": "string",
		"code": "string",
		"msg": "string",
		"flowType": "string",
		"id": "string",
		"amendStatus": "string",
		"ErrorCode": "string",
		"ErrorMessage": "string",
		"srmsReqOrderID": "string",
		"lcCreatedOn": "string",
		"draftCount": "string",
		"draftAmount": "string",
		"deletedCount": "string",
		"deletedAmount": "string",
		"selfApprovedCount": "string",
		"selfApprovedAmount": "string",
		"totalCount": "string",
		"totalAmount": "string",
		"fileId": "string",
		"amountType": "string",
		"otherAmendments": "string",
		"amendCharges": "string",
		"chargesPaid": "string",
		"creditAmount": "string",
		"amendmentReference": "string",
		"amendmentDate": "string",
		"amendmentApprovedDate": "string",
		"lcType": "string",
		"amendmentExpiryDate": "string",
		"utilizedAmount": "string",
		"importLCId": "string",
		"referenceNomatch": "string",
		"lcSRMSId": "string",
		"branchName": "string",
		"country": "string",
		"city": "string",
		"bankName": "string",
		"iban": "string",
		"bic": "string",
		"countryRegion": "string",
		"zipcode": "string",
		"bankAddress": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"lcReferenceNo",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "TradeFinance",
		tableName: "LetterOfCredit"
	};

	Object.freeze(config);

	return config;
})